### ISSUE TITLE
Search API returns wrong parent identifier

### ISSUE THREAD

**Issue by palviggi-flagbit** [akeneo/pim-community-dev#12393]
:bug: **I'm reporting a Bug** :bug:

When using the search api (via Akeneo Connector for Magento), we are getting wrong info on the "parent" field.

The filter used in this case is only "family NOT IN {list}", to get only one family. 
![incorrect_data_search](https://user-images.githubusercontent.com/54845597/86244739-b42d7800-bba8-11ea-91f7-c36aaeea3813.png)

Searching for the product directly returns the correct info
![correct_data](https://user-images.githubusercontent.com/54845597/86244850-dc1cdb80-bba8-11ea-9f58-8e4bc1c90881.png)

We also tried to use only the parent filter, and we get a completely different product in that case. 
The product returned as a parent in here, does have a child, but it's not marked as such.

The csv export returns the correct data, and the Akeneo admin shows all the correct information as well.

The server was upgraded last week.
[akeneo-pim-system-info_2020-07-01_14 33.txt](https://github.com/akeneo/pim-community-dev/files/4857892/akeneo-pim-system-info_2020-07-01_14.33.txt)

**Comment by valerie-schneider** [comment]
Hello there! 

This issue was spotted internally and fixed by the patch 4.0.33. 
On which version are you currently? 

Best, 
Valérie

**Comment by palviggi-flagbit** [comment]
4.0.34

**Comment by palviggi-flagbit** [comment]
@valerie-schneider I updated an instance to the last version (4.0.36), it's still failing giving bad results
