### ISSUE TITLE
Mapping overriddes not completely replaced

### ISSUE THREAD

**Issue by xabbuh** [akeneo/pim-community-dev#3732]
I use MongoDB to store product data and override the entity class for product attributes like this to be able to add some custom data to all attributes:

``` yaml
akeneo_storage_utils:
    mapping_overrides:
        -
            original: Pim\Bundle\CatalogBundle\Entity\Attribute
            override: AppBundle\Entity\Attribute
```

However, I still experience places where Akeneo happens to try to access the original class. I believe this is due to the fact that in the Doctrine class metadata there are still references to the old class name. For example, the mapping for the `ProductValue` class tells us that the `attribute` fields target entity is `Pim\Bundle\CatalogBundle\Entity\Attribute`.

The issue could be solved by doing some more work in the `Akeneo\Bundle\StorageUtilsBundle\Doctrine\MongoDBODM\MappingsOverrideConfigurator` class like this:

``` php
public function configure(ClassMetadata $metadata, array $mappingOverrides, $configuration)
{
    if (!$metadata instanceof ClassMetadataInfo) {
        throw new \InvalidArgumentException(
            'This configurator only handles "Doctrine\ODM\MongoDB\Mapping\ClassMetadataInfo".'
        );
    }
    if (!$configuration instanceof Configuration) {
        throw new \InvalidArgumentException(
            'This configurator only handles "Doctrine\ODM\MongoDB\Configuration".'
        );
    }

    foreach ($mappingOverrides as $override) {
        if ($override['override'] === $metadata->getName()) {
            $metadata->isMappedSuperclass = false;
            $this->setAssociationMappings($metadata, $configuration);
        }
        if ($override['original'] === $metadata->getName()) {
            $metadata->isMappedSuperclass = true;
            $this->unsetAssociationMappings($metadata);
        }

        // THIS CODE IS NEW
        foreach ($metadata->fieldMappings as $name => $mappingConfiguration) {
            if (isset($mappingConfiguration['targetEntity']) && $override['original'] === $mappingConfiguration['targetEntity']) {
                $metadata->fieldMappings[$name]['targetEntity'] = $override['override'];
            }
        }
        // END OF THE NEW CODE
    }

    return $metadata;
}
```

However, I am not sure if that really is the right solution or if there is another place where these changes (or similar ones) should be done. So I appreciate any feedback from you about this.

**Comment by xabbuh** [comment]
ping :)

I would be willing to create a pull request if someone confirms that this is indeed a bug. Please feel free to let me know if you need any further information.

**Comment by nidup** [comment]
Hi @xabbuh 

First sorry for the late answer and thank you a lot for raising this issue, this topic is very interesting but is quite complex, so let's summarize to have clear ideas :)

Let's start by the use of full doctrine ORM storage (products, product values and attributes in mysql),

1 - Replace a model interface by a doctrine entity

We originaly took inspiration from http://symfony.com/doc/2.7/cookbook/doctrine/resolve_target_entity.html

In our doctrine mapping, we always use interfaces to allow to override entities in projects, for instance https://github.com/akeneo/pim-community-dev/blob/1.4/src/Pim/Bundle/CatalogBundle/Resources/config/model/doctrine/ProductValue.orm.yml#L66

Then we use a compiler pass to provide the mapping from the model interface to the entity class https://github.com/akeneo/pim-community-dev/blob/1.4/src/Pim/Bundle/CatalogBundle/DependencyInjection/Compiler/ResolveDoctrineTargetModelPass.php

This compiler pass extends the following one which takes care of calling 'addResolveTargetEntity' on a dedicated doctrine listener  https://github.com/akeneo/pim-community-dev/blob/1.4/src/Akeneo/Bundle/StorageUtilsBundle/DependencyInjection/Compiler/AbstractResolveDoctrineTargetModelPass.php 

For the CatalogBundle, the entity classes are defined here https://github.com/akeneo/pim-community-dev/blob/1.4/src/Pim/Bundle/CatalogBundle/Resources/config/entities.yml#L14

By overriding this parameter, we can override an entity, BTW, we take care to always use the model interface in our business code to prevent any override issues (attribute and categories are common use cases, there are still known issues with Family for instance).

Issue with this original solution is:
 - we need to copy/paste the whole mapping when we override an entity (and that's a pb for us because we want to simplify the life of integrators as much as possible)
 - we have to create different tables (in some cases when adding relations), one for the original entity, one for the overriden entity you need

2 - Avoid to copy / paste the whole overriden mapping

In 1.4, we introduced the mapping_override configuration to fix the 2 previous reasons.

The mapping_override configuration is handled by the following class and takes care of "copying" the the original doctrine mapping to the overriden mapping and to mark the original class as MappedSuperclass to be able to use the same table https://github.com/akeneo/pim-community-dev/blob/1.4/src/Akeneo/Bundle/StorageUtilsBundle/Doctrine/ORM/MappingsOverrideConfigurator.php

3 - The case of MongoDB storage

When using MongoDB storage, products (and few related models) are stored as documents but we keep other models in Mysql (store product data is a very good MongoDB use case but, imho, does not bring any value for storing more standard models).

The exact same strategy than in 1) and 2) has been used for MongoDB documents.

The difficulty comes from the relations between MongoDB documents and Mysql entities.

To do this link we use our own MongoDBODM Types (Entity and Entities), you can notice that we use entity FQCN here and not the model interface https://github.com/akeneo/pim-community-dev/blob/1.4/src/Pim/Bundle/CatalogBundle/Resources/config/model/doctrine/ProductValue.mongodb.yml#L25

You can also see that, as for ORM, we use interfaces for models that are also stored as documents or embedded documents https://github.com/akeneo/pim-community-dev/blob/1.4/src/Pim/Bundle/CatalogBundle/Resources/config/model/doctrine/ProductValue.mongodb.yml#L30.

The entity type is defined here https://github.com/akeneo/pim-community-dev/blob/1.4/src/Akeneo/Bundle/StorageUtilsBundle/Doctrine/MongoDBODM/Types/Entity.php

A subscriber handles the preUpdate and postLoad of this entity coming from mysql to provide a "standard" developer experience when we manipulate products https://github.com/akeneo/pim-community-dev/blob/1.4/src/Akeneo/Bundle/StorageUtilsBundle/EventSubscriber/MongoDBODM/EntityTypeSubscriber.php

4 - What about this issue and how to fix it?

This issue has already been raised internaly by the core team but has never been fixed :)

I quickly tested your fix and it works but I think you don't change here the class really responsible of the issue, ideally, as for pure ORM storage, we should be able to use the AttributeInterface in the ProductValue MongoDB mapping.

So, I think we could dig into AbstractResolveDoctrineTargetModelPass to see if we can provide the same behavior between pure ORM and hybrid storage ORM/MongoDB.

We should fix it in a v1.4 patch (it imposes us to avoid BC Break, but if we change this kind of internal classes, it will be ok).

You proposed to write a PR and we would be very glad to count you as our contributors, if you're interested, I will be happy to work with you on this topic, to be able to merge the PR at the end, i would ask you to read and sign our contributor agreement http://www.akeneo.com/contributor-license-agreement/ :)

**Comment by xabbuh** [comment]
Hi Nicolas,

thank you very much for your detailed response (sadly I didn't find time earlier to read it completely).

I think you are raising a valid point when you talk about using the interface instead of a concrete class name in the MongoDB mapping configuration. However, I also think that this is a bit different use case and we are actually talking about two different issues:

Not using the interface in the MongoDB mapping will only become a problem when one changed the value of the `pim_catalog.entity.attribute.class` parameter (given the example you linked to in your comment). You would then have two different classes in your metadata that are denoted to be the contract for holding attribute related data.

I agree that this will be an issue and it must be solved in a different way. A possible solution I see for this is to have a new event listener that is triggered when the metadata for MongoDB documents are loaded. This listener would check each document for properties of type `entity` and will then apply the resolved target map (which would need to be passed to the listener through the DI container) to the `targetEntity` attribute.

However, the issue that I had is a bit different and would still be there if we solved the other one. Given that we already resolved the target entity resolving issue (where, for example, the `Pim\Bundle\CatalogBundle\Model\AttributeInterface` would have been resolved to the `Pim\Bundle\CatalogBundle\Entity\Attribute` class. If I then added a mapping override config entry as shown in the initial issue description, the `targetEntity` metadata property of the `ProductValue` document would still refer to the `Pim\Bundle\CatalogBundle\Entity\Attribute` class. That's where my proposed change for the `MappingsOverrideConfigurator` class fixes the issue (you already do something similar for associations that have built-in Doctrine support, see https://github.com/akeneo/pim-community-dev/blob/1.4/src/Akeneo/Bundle/StorageUtilsBundle/Doctrine/ORM/MappingsOverrideConfigurator.php#L62-L82). So if I did not missing anything, the proposed change will simply fix and edge case in the `MappingsOverrideConfigurator` when using the hybrid storage.

By the way, in the meantime I already signed the CLA. :)

**Comment by nidup** [comment]
Hi @xabbuh !
Sorry for the late answer, you're right we have 2 different issues there :)
Could be very nice if you could do a Pull Request to fix the MappingsOverrideConfigurator and update the related phpspec MappingsOverrideConfiguratorSpec.
I will be happy to check that everything running fine with our continuous integration (to run all behat scenario) and to merge it.
Thank you!

**Comment by nidup** [comment]
Hi @xabbuh 

You may be interested by this PR https://github.com/akeneo/pim-community-dev/pull/3999 
Especially this file https://github.com/akeneo/pim-community-dev/pull/3999/files#diff-4d97caaed927eb8dbfdaaab7ea499912

Cheers!

**Comment by xabbuh** [comment]
@nidup It's intended to fix the other issue you pointed out here, right?

By the way, I didn't forget about this issue (I am hopefully able to come up with a fix for it next week).

**Comment by nidup** [comment]
Yes, it fixes the second issue, we'll need to test / double check if it eases the fix of the first one.

**Comment by jjanvier** [comment]
Hello @xabbuh 

I think you problem is now solved with this PR https://github.com/akeneo/pim-community-dev/pull/3999. Could you check that it works for you by backporting it to your project please?

This listener is the key of the fix https://github.com/akeneo/pim-community-dev/pull/3999/files#diff-4d97caaed927eb8dbfdaaab7ea499912

**Comment by aRn0D** [comment]
ping @xabbuh do the PR fix this issue? Can you/we close it?

**Comment by xabbuh** [comment]
@nidup @jjanvier @aRn0D Sorry for the delay. As far as I can see this does not fix the first issue, but I'll recheck that with my colleague who discovered the issue and update you soon.

**Comment by pierallard** [comment]
Any update about this one @xabbuh ? :)
