### ISSUE TITLE
Limit of 20 attribute-groups product edit form in 1.7

### ISSUE THREAD

**Issue by patrickzzz** [akeneo/pim-community-dev#6054]
Hello everyone..

I'm reporting a bug on 1.7:

The product-edit-form only shows first 20 attribute-groups.. 

This is due to a new limit on the rest AttributeGroupController:
See: https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Bundle/EnrichBundle/Controller/Rest/AttributeGroupController.php#L76

Thanks for checking!

**Comment by mickaelandrieu** [comment]
Hello @patrickzzz,

you're right we have identified the issue and are actually working on a patch (https://github.com/akeneo/pim-community-dev/pull/5957).

Thank you for your help!

**Comment by a2xchip** [comment]
@patrickzzz @mickaelandrieu Sorry i was not reporting it anywhere, because this bug appeared after my own changes and i fixed it inside other bug ~related to the same changes.

**Comment by mickaelandrieu** [comment]
@a2xchip do you confirm the issue is fixed on master branch, or can you provide the link to the correct pull request?

**Comment by a2xchip** [comment]
https://github.com/akeneo/pim-community-dev/pull/5957 here it is. it is not fixed on master... i think after 1.7 it is going to be transmitted to master

**Comment by mickaelandrieu** [comment]
Thanks for information Alex!

**Comment by a2xchip** [comment]
@mickaelandrieu Keep you updated

**Comment by tamarasaurus** [comment]
Hi @patrickzzz, this issue has been fixed in v1.7.5 (available 2017-06-02)
