### ISSUE TITLE
Error in install script for 2.0.4

### ISSUE THREAD

**Issue by pizzachip** [akeneo/pim-community-dev#7054]
**I'm reporting a Bug**
This error occurs when trying to run the install script. I've checked the system configuration and given the details of the system configuration and the error below.

System Information:
OS: CentOS Linux release 7.4.1708
CPUs: 2
RAM: 4GB
PHP: 7.1.10
MySQL: 5.7.20
Composer: 1.5.2
Akeneo Community: 2.0.4

All install checks OK

Failing command:
php bin/console pim:install --force --symlink --clean --env=prod

Exception:
19:36:52 ERROR     [console] Error thrown while running command "doctrine:schema:create --no-debug=1 --env=prod". Message: "Schema-Tool failed with Error 'An exception occurred while executing 'CREATE TABLE pim_catalog_product (id INT AUTO_INCREMENT NOT NULL, family_id INT DEFAULT NULL, product_model_id INT DEFAULT NULL, family_variant_id INT DEFAULT NULL, is_enabled TINYINT(1) NOT NULL, identifier VARCHAR(255) NOT NULL, raw_values json NOT NULL COMMENT '(DC2Type:native_json)', created DATETIME NOT NULL COMMENT '(DC2Type:datetime)', updated DATETIME NOT NULL COMMENT '(DC2Type:datetime)', product_type VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_91CD19C0772E836A (identifier), INDEX IDX_91CD19C0C35E566A (family_id), INDEX IDX_91CD19C0B2C5DD70 (product_model_id), INDEX IDX_91CD19C08A37AD0 (family_variant_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB':

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json NOT NULL COMMENT '(DC2Type:native_json)', created DATETIME NOT NULL COMMENT' at line 1' while executing DDL: CREATE TABLE pim_catalog_product (id INT AUTO_INCREMENT NOT NULL, family_id INT DEFAULT NULL, product_model_id INT DEFAULT NULL, family_variant_id INT DEFAULT NULL, is_enabled TINYINT(1) NOT NULL, identifier VARCHAR(255) NOT NULL, raw_values json NOT NULL COMMENT '(DC2Type:native_json)', created DATETIME NOT NULL COMMENT '(DC2Type:datetime)', updated DATETIME NOT NULL COMMENT '(DC2Type:datetime)', product_type VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_91CD19C0772E836A (identifier), INDEX IDX_91CD19C0C35E566A (family_id), INDEX IDX_91CD19C0B2C5DD70 (product_model_id), INDEX IDX_91CD19C08A37AD0 (family_variant_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB" ["error" => Doctrine\ORM\Tools\ToolsException { …},"command" => "doctrine:schema:create --no-debug=1 --env=prod","message" => """  Schema-Tool failed with Error 'An exception occurred while executing 'CREATE TABLE pim_catalog_product (id INT AUTO_INCREMENT NOT NULL, family_id INT DEFAULT NULL, product_model_id INT DEFAULT NULL, family_variant_id INT DEFAULT NULL, is_enabled TINYINT(1) NOT NULL, identifier VARCHAR(255) NOT NULL, raw_values json NOT NULL COMMENT '(DC2Type:native_json)', created DATETIME NOT NULL COMMENT '(DC2Type:datetime)', updated DATETIME NOT NULL COMMENT '(DC2Type:datetime)', product_type VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_91CD19C0772E836A (identifier), INDEX IDX_91CD19C0C35E566A (family_id), INDEX IDX_91CD19C0B2C5DD70 (product_model_id), INDEX IDX_91CD19C08A37AD0 (family_variant_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB':\n  \n  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json NOT NULL COMMENT '(DC2Type:native_json)', created DATETIME NOT NULL COMMENT' at line 1' while executing DDL: CREATE TABLE pim_catalog_product (id INT AUTO_INCREMENT NOT NULL, family_id INT DEFAULT NULL, product_model_id INT DEFAULT NULL, family_variant_id INT DEFAULT NULL, is_enabled TINYINT(1) NOT NULL, identifier VARCHAR(255) NOT NULL, raw_values json NOT NULL COMMENT '(DC2Type:native_json)', created DATETIME NOT NULL COMMENT '(DC2Type:datetime)', updated DATETIME NOT NULL COMMENT '(DC2Type:datetime)', product_type VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_91CD19C0772E836A (identifier), INDEX IDX_91CD19C0C35E566A (family_id), INDEX IDX_91CD19C0B2C5DD70 (product_model_id), INDEX IDX_91CD19C08A37AD0 (family_variant_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB  """] []
19:36:52 ERROR     [console] Command "doctrine:schema:create --no-debug=1 --env=prod" exited with code "1" ["command" => "doctrine:schema:create --no-debug=1 --env=prod","code" => 1] []

**Comment by vdzpeter** [comment]
any process on this issue ? I'm getting the same issue

**Comment by ysmnikhil** [comment]
I faced similar issue but after refining system requirement, I fixed it. https://docs.akeneo.com/latest/install_pim/manual/system_requirements/system_requirements.html
My issue was elastic search version(6). It should be 5.5 ≤ version < 6.0

**Comment by aRn0D** [comment]
Hi Paul,

Could you upgrade to the 2.0.8 and check that you still have this problem, please?

Thank you.

**Comment by Doodoune** [comment]
Hi Paul!

Without feedback from your side @pizzachip, I close this issue.
Feel free to re-open if you still have this issue.
